Repository fjelltopp/ckanext-fjelltopp-theme, pull requests merged in 2024-10, with the labels that each got.

#29 Fjelltopp theme promoted section can be customized better
  ckanext/fjelltopp_theme/assets/css/_partials/_magic.scss
  ckanext/fjelltopp_theme/assets/css/fjelltopp-theme.scss
  ckanext/fjelltopp_theme/templates/admin/base.html
  ckanext/fjelltopp_theme/templates/group/edit_base.html
  ckanext/fjelltopp_theme/templates/group/read_base.html
  ckanext/fjelltopp_theme/templates/home/layout1.html
  ckanext/fjelltopp_theme/templates/organization/edit_base.html
  ckanext/fjelltopp_theme/templates/organization/read_base.html
  ckanext/fjelltopp_theme/templates/package/base.html
  ckanext/fjelltopp_theme/templates/page.html
  ckanext/fjelltopp_theme/templates/user/edit_base.html
  ckanext/fjelltopp_theme/templates/user/read_base.html
Labels: enhancement, minor

#32 185 - Improves page layout with additional fx blocks
  ckanext/fjelltopp_theme/templates/page.html
Labels: enhancement, minor

#33 30 - Move "Manage" buttons into navbar
  ckanext/fjelltopp_theme/assets/css/fjelltopp-theme.scss
  ckanext/fjelltopp_theme/templates/group/edit_base.html
  ckanext/fjelltopp_theme/templates/group/read_base.html
  ckanext/fjelltopp_theme/templates/organization/edit_base.html
  ckanext/fjelltopp_theme/templates/organization/read_base.html
  ckanext/fjelltopp_theme/templates/package/edit_base.html
  ckanext/fjelltopp_theme/templates/package/read_base.html
  ckanext/fjelltopp_theme/templates/user/read_base.html
Labels: enhancement, minor

#34 193 - Fix "add dataset is a drop down for no reason"
  ckanext/fjelltopp_theme/templates/snippets/add_dataset.html
  ckanext/fjelltopp_theme/templates/snippets/dataset_selector.html
  ckanext/fjelltopp_theme/templates/user/dashboard_datasets.html
Labels: enhancement, minor

#39 38 - Data search big input is under the wrapper of left bar
  ckanext/fjelltopp_theme/assets/css/fjelltopp-theme.scss
Labels: bug, minor

#41 40 - Cosmetic theme improvements for fjelltopp-theme
  ckanext/fjelltopp_theme/assets/css/fjelltopp-theme.scss
  ckanext/fjelltopp_theme/templates/package/search.html
  ckanext/fjelltopp_theme/templates/snippets/add_dataset.html
Labels: enhancement, minor

#43 Fix the 'Add Dataset' button in package/search
  ckanext/fjelltopp_theme/assets/css/fjelltopp-theme.scss
  ckanext/fjelltopp_theme/templates/snippets/add_dataset.html
Labels: bug, minor

#31 feat: remove shadowed wrapper
  ckanext/fjelltopp_theme/assets/css/fjelltopp-theme.scss
  ckanext/fjelltopp_theme/templates/package/base.html
  ckanext/fjelltopp_theme/templates/user/activity_stream.html
  ckanext/fjelltopp_theme/templates/user/api_tokens.html
Labels: minor
