Repository fjelltopp/ckanext-fjelltopp-theme, pull requests merged in 2024-09, with the labels that each got.

#14 fix: give webassets unique names
  .gitignore
  ckanext/fjelltopp_theme/assets/webassets.yml
Labels: bug, patch

#15 Add Organizations to menu bar
  ckanext/fjelltopp_theme/templates/header.html
  ckanext/fjelltopp_theme/templates/user/account_header.html
Labels: patch

#16 Adding a new resource to an existing dataset causes a bug
  ckanext/fjelltopp_theme/assets/css/fjelltopp-theme.scss
  ckanext/fjelltopp_theme/templates/package/new_resource_not_draft.html
Labels: bug, patch

#17 ZaRR dataset read page to look like WHO-AFRO
  ckanext/fjelltopp_theme/assets/css/_partials/_config.scss
  ckanext/fjelltopp_theme/assets/css/_partials/_magic.scss
  ckanext/fjelltopp_theme/assets/css/fjelltopp-theme.scss
  ckanext/fjelltopp_theme/assets/css/palette.css
  ckanext/fjelltopp_theme/helpers.py
  ckanext/fjelltopp_theme/plugin.py
  ckanext/fjelltopp_theme/templates/package/base.html
  ckanext/fjelltopp_theme/templates/package/read.html
  ckanext/fjelltopp_theme/templates/package/read_base.html
  ckanext/fjelltopp_theme/templates/package/resource_read.html
  ckanext/fjelltopp_theme/templates/package/snippets/additional_info.html
  ckanext/fjelltopp_theme/templates/page.html
  ckanext/fjelltopp_theme/templates/snippets/ui/linear_gradient.html
Labels: enhancement, minor

#19 18 more UI updates
  ckanext/fjelltopp_theme/assets/css/_partials/_magic.scss
  ckanext/fjelltopp_theme/assets/css/fjelltopp-theme.scss
  ckanext/fjelltopp_theme/assets/css/fontawesome.css
  ckanext/fjelltopp_theme/assets/webassets.yml
  ckanext/fjelltopp_theme/public/fonts/fa-brands-400.ttf
  ckanext/fjelltopp_theme/public/fonts/fa-brands-400.woff2
  ckanext/fjelltopp_theme/public/fonts/fa-regular-400.ttf
  ckanext/fjelltopp_theme/public/fonts/fa-regular-400.woff2
  ckanext/fjelltopp_theme/public/fonts/fa-solid-900.ttf
  ckanext/fjelltopp_theme/public/fonts/fa-solid-900.woff2
  ckanext/fjelltopp_theme/public/fonts/fa-v4compatibility.ttf
  ckanext/fjelltopp_theme/public/fonts/fa-v4compatibility.woff2
  ckanext/fjelltopp_theme/templates/admin/base.html
  ckanext/fjelltopp_theme/templates/group/about.html
  ckanext/fjelltopp_theme/templates/group/activity_stream.html
  ckanext/fjelltopp_theme/templates/group/edit_base.html
  ckanext/fjelltopp_theme/templates/group/read.html
  ckanext/fjelltopp_theme/templates/group/read_base.html
  ckanext/fjelltopp_theme/templates/group/snippets/info.html
  ckanext/fjelltopp_theme/templates/organization/about.html
  ckanext/fjelltopp_theme/templates/organization/activity_stream.html
  ckanext/fjelltopp_theme/templates/organization/bulk_process.html
  ckanext/fjelltopp_theme/templates/organization/edit_base.html
  ckanext/fjelltopp_theme/templates/organization/read.html
  ckanext/fjelltopp_theme/templates/organization/read_base.html
  ckanext/fjelltopp_theme/templates/organization/snippets/organization.html
  ckanext/fjelltopp_theme/templates/package/base.html
  ckanext/fjelltopp_theme/templates/package/search.html
  ckanext/fjelltopp_theme/templates/page.html
  ckanext/fjelltopp_theme/templates/snippets/dataset_selector.html
  ckanext/fjelltopp_theme/templates/snippets/facet_list.html
  ckanext/fjelltopp_theme/templates/snippets/fx/circle.html
  ckanext/fjelltopp_theme/templates/snippets/home_breadcrumb_item.html
  ckanext/fjelltopp_theme/templates/snippets/package_item.html
  ckanext/fjelltopp_theme/templates/snippets/search_form.html
  ckanext/fjelltopp_theme/templates/snippets/ui/linear_gradient.html
  ckanext/fjelltopp_theme/templates/user/edit.html
  ckanext/fjelltopp_theme/templates/user/edit_base.html
  ckanext/fjelltopp_theme/templates/user/read_base.html
Labels: enhancement, major

#20 Changes 'Organization' to 'Organizations' in the datahub stats in footer
  ckanext/fjelltopp_theme/helpers.py
Labels: enhancement, minor

#22 21- Updates from feedback (mission)
  ckanext/fjelltopp_theme/templates/admin/base.html
  ckanext/fjelltopp_theme/templates/header.html
  ckanext/fjelltopp_theme/templates/snippets/footer_links.html
  ckanext/fjelltopp_theme/templates/snippets/subscribe_to_updates.html
  ckanext/fjelltopp_theme/templates/user/account_header.html
  ckanext/fjelltopp_theme/templates/user/dashboard.html
  ckanext/fjelltopp_theme/templates/user/dashboard_datasets.html
  ckanext/fjelltopp_theme/templates/user/login.html
  ckanext/fjelltopp_theme/templates/user/snippets/login_form.html
Labels: bug, minor

#25 24 - New group or organization pages have issues because of new UI
  ckanext/fjelltopp_theme/templates/group/edit_base.html
  ckanext/fjelltopp_theme/templates/organization/edit_base.html
Labels: bug, minor

#27 26 - A small changes to manage button design
  ckanext/fjelltopp_theme/assets/css/fjelltopp-theme.scss
Labels: minor
